#!/bin/bash

file_my_cnf="$HOME/my.cnf"
file_config="database-backup.config"

function source_config {
    if [ ! -f "$file_config" ]; then
        echo "Missing configuration file ($file_config)"
        exit 1
    fi
    if ! grep -q "DATABASE_BACKUPS_PATH" "$file_config"; then
        echo "The configuration file does not contain the backups directory path"
        exit 1
    fi
    source $file_config
}

function backup {
    timestamp=$(date +"%Y-%m-%d_%H%M")
    file_backup="$DATABASE_BACKUPS_PATH/$timestamp.sql.gz"
    mkdir -p $DATABASE_BACKUPS_PATH && mysqldump --defaults-file="$file_my_cnf" --all-databases --no-tablespaces | gzip > $file_backup && chmod 600 $file_backup
}

function cleanup {
    if [[ -z "${DATABASE_BACKUPS_KEEP_FOR_DAYS}" ]]; then
        echo "Skipping the cleanup of backups as the number of days for keeping them is not configured"
    else
        echo "Cleaning up backups older than $DATABASE_BACKUPS_KEEP_FOR_DAYS days"
        find $DATABASE_BACKUPS_PATH -type f -name "*.sql.gz" -mtime +$DATABASE_BACKUPS_KEEP_FOR_DAYS -delete
    fi
}

source_config
backup
cleanup
